version: '2'
services:
  server:
    build: .
    ports:
      - "80:8080"
    environment:
      CIDER_SERVER_DSN: default=root:${CIDER_MYSQL_ROOT}@tcp4(mysql:3306)/cider
  mysql:
    image: mysql
#    ports:
#      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${CIDER_MYSQL_ROOT}
#    volumes:
#      - ./docker/dump:/docker-entrypoint-initdb.d